### PR TITLE
Allow attributes to take a block which consumes a returned array of attributes

### PR DESCRIPTION
**Pull request by toxaq**
We use json backed and other custom attributes on various sub classes (typically STI) that  can appear in the same collection. We then store the available custom attributes for that class on the class and reference it in rabl view like this

    attributes *@root.class.api_attributes

This works ok but can't be used in a collection. As such I've extended attributes to take a block which can access the object as transform the above into

    attributes{|r| r.class.api_attributes}

api_attributes is just something like:

    def api_attributes
       [:name, :public_key, :url]
    end

Obviously the attributes returned can be completely dynamic as it's simply a method call. This is useful to me so just checking if it's useful to the project? Happy to change documentation of this first stab is wanted.

Note: I realise you can do this with extends but unless the performance hole has been fixed since last I looked we wouldn't use that and this still makes for cleaner code when using view helper methods alot.

### CODE REVIEW

**Comment by toxaq** [comment]
I take it that's a no then...

**Comment by nesquena** [comment]
Hey Scott, sorry about not responding back in 2017. I went ahead now and closed all old PRs since for a long stretch I wasn't able to review them. I was looking for someone else to +1 any PRs or mention they had tested it before merging since my main priority is to avoid breakages.  I am no longer actively maintaining RABL myself at this point, but I would be happy for others to help keep the project going.

**Comment by toxaq** [comment]
No worries Nathan. I'm still using a fork with the above feature as it's really powerful but, like you said, it's not had any traction here. 

I also just wanted to thank you for creating this gem and all the effort you've put in. It's been great to work with. Thank you.

**Comment by nesquena** [comment]
That's great, I am genuinely amazed and honored that people still use RABL nearly 8+ years after I first put it together. Glad you've found it helpful and glad you were able to get this working as needed in your fork.

**Pull request closed without merging**
