### PR TITLE
Fix problem of usage rabl 0.13.0 with Rails 5 and active cache

### PR DESCRIPTION
**Pull request by le0pard**

### CODE REVIEW

**Comment by nesquena** [comment]
Thanks!

**Comment by le0pard** [comment]
@nesquena thanks, but looks like I need fix something, if it was reverted, isn't it?

**Comment by nesquena** [comment]
Did you mean to just remove all that code in the digestor?

**Comment by le0pard** [comment]
I remove it, because Rails 5 Digestor doesn't have an initializer and the 3rd parameter is actually the dependencies and not the options. We're already calling `Digestor.digest` with the same signature as the built-in digest, so we should just use that. After this changes I checked it on staging server of my app and cache in rabl continue working (output by redis monitor):
```
1476651478.597309 [0 127.0.0.1:9318] "mget" "cache:rabl/inboxes/1-20160201121619264569-86-0//hash/43ff2ca40b70ad2989bc2a776124e03e" "cache:rabl/inboxes/3-20160122094313966306-12-0//hash/43ff2ca40b70ad2989bc2a776124e03e" "cache:rabl/inboxes/74-20160202133857021443-0-0//hash/43ff2ca40b70ad2989bc2a776124e03e" ""
1476651478.609248 [0 127.0.0.1:9318] "mget" "cache:rabl/inboxes/2-20160121173326340571-558-0//hash/43ff2ca40b70ad2989bc2a776124e03e" ""
1476651478.633126 [0 127.0.0.1:9318] "mget" "cache:rabl/inboxes/4-20161013151423574157-104-0//hash/43ff2ca40b70ad2989bc2a776124e03e" "cache:rabl/inboxes/5-20161013151423574157-165-0//hash/43ff2ca40b70ad2989bc2a776124e03e" "cache:rabl/inboxes/39-20161013151423574157-0-0//hash/43ff2ca40b70ad2989bc2a776124e03e" "cache:rabl/inboxes/68-20161013151423574157-0-0//hash/43ff2ca40b70ad2989bc2a776124e03e" ""
```

**Comment by nesquena** [comment]
Thanks, added back here then https://github.com/nesquena/rabl/commit/f6d967294105a7d486d541e5b52cc46388f9d75b

**Comment by le0pard** [comment]
@nesquena thank you too.

**Comment by jhawthorn** [comment]
@nesquena can we get a gem version cut for this? The existing versions do not work on rails 5.

**Comment by nesquena** [comment]
@jhawthorn Yep pushed 0.13.1 just now. Thanks for the reminder

**Pull request merged**
