### PR TITLE
Add option to camelize keys

### LINKED ISSUE #469: Option to camelize attributes
The standard in Ruby is using snake_case but in Javascript, arguably the main JSON consumer, the standard is camelCase. I would like my js projects to be a little more consistent so would you be open to an option that camelizes all attributes?

### PR DESCRIPTION
**Pull request by rstrand**
I have added a configuration option `camelize_keys` which camel cases attribute keys. This should fix #469.

I added some new tests which pass, but the existing tests don't seem to be passing. I don't think my changes break anything thought.

### CODE REVIEW

**Comment by apuntovanini** [comment]
@nesquena any plans to merge this?

**Comment by nesquena** [comment]
Thanks for the reminder. Merged now.

**Comment by apuntovanini** [comment]
Great! Thank you! Would you release a new version or suggest to use #master instead? I love rabl, we use it extensively, let me know if there's anything we can do

**Comment by nesquena** [comment]
I'll release a new version soon. Glad to hear that you find RABL useful, I built it many years ago now. I don't have the time to maintain it much anymore unfortunately. Always looking for / appreciate new contributors :)

**Comment by apuntovanini** [comment]
I guess there are no good alternatives out there, or do you know any? I'll look through the issues and check if I find something I can work on

**Comment by badosu** [comment]
This would be relevant for us as well, currently using reference to master.

Let me know how I can help proceeding with this.

**Comment by apuntovanini** [comment]
@rstrand I don't know if it's related to your PR or not, but there's an issue regarding camelize_props. It does camelize all props but not the nested ones...what do you think? I could work on a PR @nesquena tomorrow

**Comment by apuntovanini** [comment]
@rstrand ok, I’ll check it out! Just out of curiosity, what do you use instead?

**Comment by rstrand** [comment]
@apuntovanini I've been using ActiveModelSerializers using the key transform option (https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/general/configuration_options.md).

JSONAPI-RB also looks good if your JSON schema is flexible http://jsonapi-rb.org/

**Comment by apuntovanini** [comment]
@rstrand thank you very much for the suggestions, I'll check them out
I added some failing tests, but I still cannot grasp how to fix the nested uncamelized props..
Any ideas @nesquena?

**Pull request merged**
