### PR TITLE
Fix compatibility with Ruby 1.9.3 and 2.0.0

### PR DESCRIPTION
**Pull request by domcleal**
The named arguments syntax used for the Rails 5 `digest` method is only
valid on Ruby 2.1 or higher (or 2.0.0 if default values are supplied),
causing an error parsing the lib/rabl/digestor.rb source on these
older versions.

    SyntaxError: rabl-0.13.0/lib/rabl/digestor.rb:6: syntax error, unexpected ','
          def self.digest(name:, finder:, **options)

The support for different Rails versions has been moved into separate
files that can be loaded only when required.

---

Broken since a8d7cb3 in 0.13.0. Should fix the Travis CI matrix too by pinning ActiveRecord to a version that's compatible with each tested Ruby version.

### CODE REVIEW

**Comment by databyte** [comment]
Looks good, but it looks like we're missing a fixture for Rails 5. I may add that first before asking anyone to accept this PR. I don't know if you want to try your hand at it or wait for me to do it.

**Comment by domcleal** [comment]
Oh, well-spotted - I was wondering if/where multiple Rails versions were being tested. I'll add a new fixture to this PR shortly.

**Comment by databyte** [comment]
Yeah, you can either copy over an existing one and then "upgrade" it. Or `rails new` it and then link over models and views. Notice how they all point to the same set of models and view files using links and it's not just copied over. That helps test the same files for backwards compatibility across all rails versions. The only thing unique about each Rails version is in the controllers since they changed a little along the way.

If you do setup a rails app, [here's how to test it](https://github.com/nesquena/rabl/blob/master/Rakefile#L51) - you may need to run `rake test:setup` first.

**Comment by domcleal** [comment]
Thanks for the hints, that's what I've done. There are a couple of test failures remaining that I can't figure out immediately:

1. `PostsController renderer setup => wrong number of arguments (given 3, expected 0) occured at test/controllers/posts_controller_test.rb:145:in 'block (3 levels) in <main>'` - there's a bug in the Rails 5 Digestor file where it calls `Digestor.new` with three (unsupported) arguments. I'm unsure precisely what this code should be doing, so haven't been able to fix it.
1. `PostsController mime_type asserts contains post title => 784: unexpected token at '<!DOCTYPE html>` - the HTML layout is being included into the `rabl_test_v1` response, leaving the JSON surrounded by HTML.

**Comment by databyte** [comment]
It's a pathing issue - I've fixed it off a pull from your repo. If you give me commit rights to your fork, I can push up to your branch and it'll update the PR.

**Comment by domcleal** [comment]
Sure, commit invite sent. Thanks!

**Comment by domcleal** [comment]
I'm not sure that 065fc34 contains the new/moved files, just the removals?

**Comment by databyte** [comment]
Ah shit. One minute.

**Comment by databyte** [comment]
Yeah, somehow the symlinking wasn't the silver bullet... I'm still working off of your branch, I'll push up a solution shortly (hopefully) and then we'll need to create a new PR. At least the tests pass overall, just need to add in the Rails 5 fixture to make sure it works.

**Pull request merged**
